### PR TITLE
Support for TileStache's 'safe' layout

### PR DESCRIPTION
**Pull request by sethfitz**
This adds support for [TileStache's 'safe' directory layout](http://tilestache.org/doc/#caches) by using a URL similar to `file:///tmp/foo?safe=true`.

This also corrects grid filenames (to `*.json`) when writing.

### CODE REVIEW

**Comment by springmeyer** [comment]
Looks good. Could you add tests?

**Comment by sethfitz** [comment]
Sure!

**Comment by sethfitz** [comment]
Cloning the `readonly` fileset is probably overkill, but it's consistent.

**Comment by springmeyer** [comment]
are you missing .grid and .txt test fixures, or am I missing something?

**Comment by sethfitz** [comment]
Those are created during the `put*` tests and removed at the end of the run.

**Pull request merged**
